version: '3.3'

services:
  bds-website:
    container_name: ${REPOSITORY}
    build:
      context: .
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"