version: '3.3'

services:
  pod-admin:
    container_name: ${REPOSITORY}
    build:
      context: .
      args:
        NODE_ENV: production
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"